url: http://viveksck.github.io
baseurl: 

# Site Settings
title: Vivek Kulkarni
# Career Settings
# Default career thumbnail image.
career-img: "img/career/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
